# Generated by Django 3.2.7 on 2021-09-21 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('date', models.DateTimeField(blank=None, default=datetime.datetime(2021, 9, 21, 19, 37, 53, 778613), null=None)),
            ],
        ),
    ]
